{% set name = "noodles" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/noodles-{{ version }}.tar.gz
  sha256: 6fdd9b0501133d9d013c02eafe9ce934b295553d51fa19368c849fe48b5e9fe7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - filelock >=3.4.2,<4.0.0
    - python-graphviz >=0.19.1,<0.20.0
    - h5py >=3.6.0,<4.0.0
    - numpy >=1.22.2,<2.0.0
    - python >={{ python_min }},<4.0
    - pyxenon >=3.0.3,<4.0.0

test:
  imports:
    - noodles
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/noodles/
  summary: Worflow Engine
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
